version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vps_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_vps
      POSTGRES_PASSWORD: password_vps
      POSTGRES_DB: vps_control_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: